### ISSUE TITLE
test2.js

### ISSUE THREAD

**Issue by danielsza** [TheThingSystem/node-taas-client#1]
so this didn't work... after trying these commands the steward wouldn't start

   %  npm config set strict-ssl false
    % npm update npm -g
    % npm config set strict-ssl true

```
# sh /etc/init.d/steward stop
% cd steward
% git pull
% cd steward
% rm -rf node_modules
% npm -l install
```

   # sh /etc/init.d/steward start

So I reverted my snapshot and installed the steward again
it's up and running

daniel@ubuntu:~$ cd ~/steward/steward/
daniel@ubuntu:~/steward/steward$ sudo ./run.sh 
[sudo] password for daniel: 
info: running on Linux Debian wheezy/sid ( 3.5.0-23-generic x86_64)
info: using node v0.10.22
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
info: [devices] loading climate driver
debug: [climate] begin
info: [devices] loading gateway driver
info: [devices] loading indicator driver
info: [devices] loading lighting driver
info: [devices] loading media driver
debug: [media] begin
info: [devices] loading motive driver
debug: [motive] begin
info: [devices] loading presence driver
info: [devices] loading sensor driver
info: [devices] loading switch driver
info: [devices] loading wearable driver
debug: [wearable] begin
info: [climate] loading ecobee-control driver
info: [climate] loading flower-power-sensor driver
info: [climate] loading koubachi-sensor driver
info: [climate] loading nest-control driver
info: [climate] loading netatmo-sensor driver
info: [climate] loading oregon-scientific-sensor driver
info: [climate] loading samsung-control driver
info: [climate] loading yoctopuce-co2 driver
info: [climate] loading yoctopuce-light driver
info: [climate] loading yoctopuce-meteo driver
info: [climate] loading yoctopuce-voc driver
info: [discovery] SSDP listening on http://0.0.0.0:1900
info: [gateway] loading automatic-cloud gateway
info: [gateway] loading ecobee-cloud gateway
info: [devices] failing ecobee-cloud gateway (continuing) diagnostic=Cannot find module 'ecobee-api'
info: [gateway] loading flower-power-cloud gateway
info: [gateway] loading insteon-9761 gateway
info: [gateway] loading koubachi-cloud gateway
info: [gateway] loading lockitron-cloud gateway
info: [gateway] loading nest-cloud gateway
info: [gateway] loading netatmo-cloud gateway
info: [gateway] loading openzwave-usb gateway
info: [gateway] loading reelyactive-reel gateway
info: [gateway] loading rfxcom-usb gateway
info: [gateway] loading tesla-cloud gateway
info: [gateway] loading wink-cloud gateway
info: [gateway] loading yoctopuce-hub gateway
info: [gateway] loading zigbee-gmo gateway
info: [discovery] reelyactive-reel driver listening on  udp://_:7018
info: [indicator] loading dweetio-sensor driver
info: [indicator] loading irtoy-infrared driver
info: [indicator] loading mqtt-text driver
info: [indicator] loading nma-text driver
info: [indicator] loading prowl-text driver
info: [indicator] loading wink-dial driver
info: [indicator] loading wink-nimbus driver
info: [indicator] loading xively-sensor driver
info: [lighting] loading blink1-led driver
info: [lighting] loading blinkstick-led driver
info: [lighting] loading heroicrobotics driver
info: [lighting] loading hue driver
info: [lighting] loading insteon-led driver
info: [lighting] loading robosmart-led driver
info: [lighting] loading tabu-lumen driver
info: [lighting] loading tcpi-led driver
info: [lighting] loading yoctopuce-color driver
info: [lighting] loading yoctopuce-powercolor driver
info: [discovery] PixelPusher listening on udp://_:7331
info: [media] loading audio-sonos driver
info: [media] loading camera-axis driver
info: [media] loading video-appletv driver
info: [media] loading video-chromecast driver
info: [media] loading video-roku driver
info: [motive] loading automatic-vehicle driver
info: [motive] loading crazyflie-3d driver
info: [motive] loading irobot-floor driver
info: [motive] loading lockitron-lock driver
info: [motive] loading tesla-model-s driver
info: [presence] loading fob driver
info: [presence] loading mobile-mqtt driver
info: [presence] loading reelyactive-tag driver
info: [switch] loading insteon-dimmer driver
info: [switch] loading insteon-onoff driver
info: [switch] loading wemo-onoff driver
info: [switch] loading wink-onoff driver
info: [switch] loading wink-pivot-power-genius driver
info: [switch] loading zwave-dimmer driver
info: [switch] loading zwave-onoff driver
info: [wearable] loading watch driver
notice: [steward] start uuid=2f402f80-da50-11e1-9b23-001c42055f14
info: [server] listening on wss://_:8888
info: [server] listening on wss://_:8887
info: [server] listening on http://*:80
info: [server] loading console route
info: [server] loading manage route
info: [server] loading oneshot route
info: [server] loading root route
info: [server] loading ble discovery
info: [server] loading mac discovery
info: [server] loading owl discovery
info: [server] loading portscan discovery
info: [server] loading ssdp discovery
info: [server] loading tsrp discovery
info: [discovery] OWL driver listening on multicast udp://224.192.32.19:22600
info: [discovery] SSDP listening on http://192.168.0.110:1900
info: [discovery] TSRP listening on multicast udp://224.0.9.1:22601
info: [discovery] UPnP listening on http://192.168.0.110:8886
info: [discovery] mDNS Bedroom Apple TV url=http://192.168.0.106:7000/
info: [devices] found Bedroom Apple TV deviceID=5, deviceType=/device/media/appletv/video
info: [sensor] loading nest-smoke driver
info: [sensor] loading texas-instruments-sensortag driver
info: [sensor] loading wemo-motion driver
info: [sensor] loading wink-spotter driver
info: [sensor] loading yoctopuce-4-20mA-Rx driver
info: [discovery] mDNS Living Room Apple TV url=http://192.168.0.115:7000/
info: [devices] found Living Room Apple TV deviceID=6, deviceType=/device/media/appletv/video
info: [discovery] UPnP front house lights url=http://192.168.0.125:49153/
info: [devices] found front house lights deviceID=3, deviceType=urn:Belkin:device:lightswitch:1
info: [discovery] UPnP hallway  3way door url=http://192.168.0.124:49153/
info: [devices] found hallway  3way door deviceID=1, deviceType=urn:Belkin:device:lightswitch:1
info: [discovery] UPnP WeMo Radio url=http://192.168.0.129:49154/
info: [devices] found WeMo Radio deviceID=4, deviceType=urn:Belkin:device:controllee:1
info: [switch] device/3 front house lights subscribe=uuid:86e22494-1dd2-11b2-b2a0-9a5eb6f4d8b2, sequence=0, seconds=1800
info: [switch] device/1 hallway  3way door subscribe=uuid:86ce1008-1dd2-11b2-b2fb-a0ac840bd3e6, sequence=0, seconds=1800
info: [switch] device/4 WeMo Radio subscribe=uuid:893ce99a-1dd2-11b2-b56a-e3c1487596ae, sequence=0, seconds=1800
info: [discovery] UPnP VPN Router TL-R600VPN url=
warning: [devices] no maker registered for TL-R600VPN
info: [discovery] PORT starting scan
info: [discovery] UPnP hallway url=http://192.168.0.122:49153/
info: [devices] found hallway deviceID=2, deviceType=urn:Belkin:device:lightswitch:1
info: [switch] device/2 hallway subscribe=uuid:8aa765f8-1dd2-11b2-8b11-b841277d4b89, sequence=0, seconds=1800
info: [gateway] nest-cloud begin 30-second scan
info: [discovery] PORT finished scan
info: [server] wss 192.168.0.110 43470 /console loopback=false, subnet=true, local=true, remoteAddress=192.168.0.110, secure=false, event=connection
warning: [server] wss 192.168.0.110 43470 /console loopback=false, subnet=true, local=true, remoteAddress=192.168.0.110, secure=false, event=access, diagnostic=unauthorized, resource=console
info: [server] wss 192.168.0.110 43471 /manage loopback=false, subnet=true, local=true, remoteAddress=192.168.0.110, secure=false, event=connection
info: [server] wss 192.168.0.110 43470 /console loopback=false, subnet=true, local=true, remoteAddress=192.168.0.110, secure=false, event=close, code=1000, message=
info: [server] wss 192.168.0.110 43471 /manage loopback=false, subnet=true, local=true, remoteAddress=192.168.0.110, secure=false, event=close, code=1000, message=

so on to the next thing

```
% npm -l install taas-client
```

I had to use  "sudo npm -l install tass-client"

this will install the client library. make sure you see this:

```
taas-client@0.4.0 node_modules/taas-client
```

which indicates that you got the latest (0.4.0) version of the library. 

I saw that and it seems to have install correctly 

then, you can then do this:

```
% cd node_modules/taas-client
% node test2.js
```

and that give me this message

daniel@ubuntu:~$ cd ~/steward/steward/
daniel@ubuntu:~/steward/steward$ cd node_modules/taas-client/
daniel@ubuntu:~/steward/steward/node_modules/taas-client$ node test2.js
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
console
{ event: 'establish', url: 'ws://ubuntu.local.:8887/console' }

/home/daniel/steward/steward/node_modules/taas-client/test2.js:9
  if (loginP) throw new Error('script should be run locally');
                    ^
Error: script should be run locally
    at switches (/home/daniel/steward/steward/node_modules/taas-client/test2.js:9:21)
    at EventEmitter.emit (events.js:98:17)
    at WebSocket.<anonymous> (/home/daniel/steward/steward/node_modules/taas-client/taas-client.js:269:10)
    at WebSocket.EventEmitter.emit (events.js:92:17)
    at WebSocket.establishConnection (/home/daniel/steward/steward/node_modules/ws/lib/WebSocket.js:679:8)
    at ClientRequest.<anonymous> (/home/daniel/steward/steward/node_modules/ws/lib/WebSocket.js:591:25)
    at ClientRequest.g (events.js:175:14)
    at ClientRequest.EventEmitter.emit (events.js:106:17)
    at Socket.socketOnData (http.js:1612:11)
    at TCP.onread (net.js:525:27)
daniel@ubuntu:~/steward/steward/node_modules/taas-client$

**Comment by mrose17** [comment]
turn on 'developer' mode for your steward and try again!

**Comment by danielsza** [comment]
I can't seem to recall how to put the steward into developer mode

**Comment by mrose17** [comment]
no worries, i have an easier fix. get version 0.4.1 of the library

```
    % cd steward/steward
    % rm -rf node_modules/taas-client
    % npm -l install taas-client
    …
    taas-client@0.4.1 node_modules/taas-client
    …        
    % cd node_modules/taas-client
    % node test2.js
```

and you should see something like this:

```
    *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
    ...
    console
    { event: 'establish', url: 'ws://localhost:8887/console' }
    done.
```

the "done." indicates success.

**Comment by danielsza** [comment]
that worked… but now there is a write error

daniel@ubuntu:~/steward/steward$ cd node_modules/taas-client
daniel@ubuntu:~/steward/steward/node_modules/taas-client$ node test2.js 
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
console
{ event: 'establish', url: 'ws://localhost:8887/console' }

/home/daniel/steward/steward/node_modules/taas-client/test2.js:13
  if (data.indexOf('read') !== -1) throw new Error('script requires write acce
                                         ^
Error: script requires write access
    at switches (/home/daniel/steward/steward/node_modules/taas-client/test2.js:13:42)
    at EventEmitter.emit (events.js:98:17)
    at WebSocket.<anonymous> (/home/daniel/steward/steward/node_modules/taas-client/taas-client.js:241:16)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/home/daniel/steward/steward/node_modules/ws/lib/WebSocket.js:647:10)
    at Receiver.opcodes.1.finish (/home/daniel/steward/steward/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/home/daniel/steward/steward/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/home/daniel/steward/steward/node_modules/ws/lib/Receiver.js:93:24)
    at firstHandler (/home/daniel/steward/steward/node_modules/ws/lib/WebSocket.js:622:22)
    at process._tickCallback (node.js:415:13)
daniel@ubuntu:~/steward/steward/node_modules/taas-client$ sudo node test2.js [sudo] password for daniel: 
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
console
{ event: 'establish', url: 'ws://localhost:8887/console' }

/home/daniel/steward/steward/node_modules/taas-client/test2.js:13
  if (data.indexOf('read') !== -1) throw new Error('script requires write acce
                                         ^
Error: script requires write access
    at switches (/home/daniel/steward/steward/node_modules/taas-client/test2.js:13:42)
    at EventEmitter.emit (events.js:98:17)
    at WebSocket.<anonymous> (/home/daniel/steward/steward/node_modules/taas-client/taas-client.js:241:16)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/home/daniel/steward/steward/node_modules/ws/lib/WebSocket.js:647:10)
    at Receiver.opcodes.1.finish (/home/daniel/steward/steward/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/home/daniel/steward/steward/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/home/daniel/steward/steward/node_modules/ws/lib/Receiver.js:93:24)
    at firstHandler (/home/daniel/steward/steward/node_modules/ws/lib/WebSocket.js:622:22)
    at process._tickCallback (node.js:415:13)
daniel@ubuntu:~/steward/steward/node_modules/taas-client$

**Comment by mrose17** [comment]
i don't understand given that you are running the script on the same machine as the steward. so, let's figure this out. go to line 13 in the file test2.js - it looks like this:

```
      if (data.indexOf('read') !== -1) throw new Error('script requires write access');
```

right above that line, add this one:

```
      console.log(data);
```

run

```
    % node test2.js
```

again and send me the output.

thanks!

**Comment by danielsza** [comment]
daniel@ubuntu:~/steward/steward/node_modules/taas-client$ node test2.js
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
console
{ event: 'establish', url: 'ws://localhost:8887/console' }
[ 'read' ]

/home/daniel/steward/steward/node_modules/taas-client/test2.js:13
  if (data.indexOf('read') !== -1) throw new Error('script requires write acce
                                         ^
Error: script requires write access
    at switches (/home/daniel/steward/steward/node_modules/taas-client/test2.js:13:42)
    at EventEmitter.emit (events.js:98:17)
    at WebSocket.<anonymous> (/home/daniel/steward/steward/node_modules/taas-client/taas-client.js:241:16)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/home/daniel/steward/steward/node_modules/ws/lib/WebSocket.js:647:10)
    at Receiver.opcodes.1.finish (/home/daniel/steward/steward/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/home/daniel/steward/steward/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/home/daniel/steward/steward/node_modules/ws/lib/Receiver.js:93:24)
    at firstHandler (/home/daniel/steward/steward/node_modules/ws/lib/WebSocket.js:622:22)
    at process._tickCallback (node.js:415:13)
daniel@ubuntu:~/steward/steward/node_modules/taas-client$

**Comment by mrose17** [comment]
well, i'm running the same code on a vanilla RPi with two z-wave devices and "it just works".

ok, let's try this. go to:

```
    http://steward.local:8887/
```

question 1: does it ask you to either

```
    create/add account
    read-only
    login
```

? if not, go to "next". otherwise, if you have previously created an account, login with that. that; otherwise click on create/add account, create an account, and then and then go back to the URL above and login with that account.

next:

now click on the "gear box" icon in the upper left-hand corner. on the new screen, look for security services.

question 2: does it say "Developer" or "Strict"? if it says "Strict", then select "Developer" and click on "Done".

then go ahead and run

```
    % node test2.js
```

again and let's see what you get… thanks for your patience!

**Comment by danielsza** [comment]
It didn’t ask to login

and it was set to strict, changed it to developer and it works…

but now a new error, I have a total of 4 wemo switches, it doesn’t seem to like that...

daniel@ubuntu:~/steward/steward/node_modules/taas-client$ node test2.js**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
console
{ event: 'establish', url: 'ws://localhost:8887/console' }
[ 'developer' ]
[Error: found 4 WeMo switches]

**Comment by mrose17** [comment]
right. ok, go to

```
http://steward.local:8887/console
```

find the two wemo switches that you want to use, and give me two device numbers, e.g., for the screen below you want device/370 and device/371:

![1](https://f.cloud.github.com/assets/400552/2354440/380955d2-a5c0-11e3-88e4-36e99a6fc5fe.png)

and then tell me which is the one that when it gets turned on manually, it should be shut off and the other one go on.

thanks,

/mtr

**Comment by danielsza** [comment]
device/1 is the 3way switch that will turn on device/2 then it should turn itself off

**Comment by mrose17** [comment]
ok, lets try this: edit test2.js look at line 94, which says this:

```
    if (switches.length !== 2) {
```

change it to

```
    if (switches.length < 2) {
```

and then run it again:

```
    % node test2.js
```

i think that should do the trick! good luck!

**Comment by danielsza** [comment]
so that seems to work now, but if it doesn’t seem to do anything. 

if I press the switch nothing happens (after disabling IFTTT)

daniel@ubuntu:~/steward/steward/node_modules/taas-client$ node test2.js
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
console
{ event: 'establish', url: 'ws://localhost:8887/console' }
[ 'developer' ]
done.
daniel@ubuntu:~/steward/steward/node_modules/taas-client$

**Comment by mrose17** [comment]
go to http://steward.local:8887/console and at the top of the screen you'll see something like this:

![1](https://f.cloud.github.com/assets/400552/2367053/345af1ac-a737-11e3-8fc0-54f51f9449c4.png)

please send me what you see on your console. also, are you sure that you "got the latest" and restarted the steward?

**Comment by danielsza** [comment]
I updated TTS on March 1st, should I update again?

**Comment by mrose17** [comment]
probably. i ran the script here and my switches work the way i think you'd want them to…

/mtr

**Comment by danielsza** [comment]
Thanks for all your help so far. I really appreciate it.

ok I ran the update and we are getting some where…

the 1st time I turn on the switch works as it should ( about 2 second delay, much better then with ifttt)
the 1st time I turn off the switch works as it should 

the 2ed time I turn on the switch works as it should
the 2ed time I turn off the switch works as it should

but now the light will turn it self on for a second, then the light turns off.
and the switch will no longer toggle the other one. 

if I restart the steward the switch works again for the first 2 times

daniel@ubuntu:~/steward/steward$ sudo ./run.sh
info: running on Linux Debian wheezy/sid ( 3.5.0-23-generic x86_64)
info: using node v0.10.22
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
info: [devices] loading climate driver
debug: [climate] begin
info: [devices] loading gateway driver
info: [devices] loading indicator driver
info: [devices] loading lighting driver
info: [devices] loading media driver
debug: [media] begin
info: [devices] loading motive driver
debug: [motive] begin
info: [devices] loading presence driver
info: [devices] loading sensor driver
info: [devices] loading switch driver
info: [devices] loading wearable driver
debug: [wearable] begin
info: [climate] loading ecobee-control driver
info: [climate] loading flower-power-sensor driver
info: [climate] loading koubachi-sensor driver
info: [climate] loading nest-control driver
info: [climate] loading netatmo-sensor driver
info: [climate] loading oregon-scientific-sensor driver
info: [climate] loading samsung-control driver
info: [climate] loading yoctopuce-meteo driver
info: [discovery] SSDP listening on http://0.0.0.0:1900
info: [gateway] loading automatic-cloud gateway
info: [gateway] loading ecobee-cloud gateway
info: [devices] failing ecobee-cloud gateway (continuing) diagnostic=Cannot find module 'ecobee-api'
info: [gateway] loading flower-power-cloud gateway
info: [gateway] loading insteon-9761 gateway
info: [gateway] loading koubachi-cloud gateway
info: [gateway] loading lockitron-cloud gateway
info: [gateway] loading nest-cloud gateway
info: [gateway] loading netatmo-cloud gateway
info: [gateway] loading openzwave-usb gateway
info: [gateway] loading reelyactive-reel gateway
info: [gateway] loading rfxcom-usb gateway
info: [gateway] loading tesla-cloud gateway
info: [gateway] loading wink-cloud gateway
info: [gateway] loading yoctopuce-hub gateway
info: [gateway] loading zigbee-gmo gateway
info: [discovery] reelyactive-reel driver listening on  udp://_:7018
info: [indicator] loading cassandra-nosql driver
info: [indicator] loading dweetio-sensor driver
info: [indicator] loading mqtt-text driver
info: [indicator] loading nma-text driver
info: [indicator] loading prowl-text driver
info: [indicator] loading wink-dial driver
info: [indicator] loading wink-nimbus driver
info: [indicator] loading xively-sensor driver
info: [lighting] loading blink1-led driver
info: [lighting] loading blinkstick-led driver
info: [lighting] loading heroicrobotics driver
info: [lighting] loading hue driver
info: [lighting] loading insteon-led driver
info: [lighting] loading lifx-bulb driver
info: [lighting] loading robosmart-led driver
info: [lighting] loading tabu-lumen driver
info: [lighting] loading tcpi-led driver
info: [lighting] loading yoctopuce-color driver
info: [lighting] loading yoctopuce-powercolor driver
info: [discovery] PixelPusher listening on udp://_:7331
info: [media] loading audio-sonos driver
info: [media] loading camera-axis driver
info: [media] loading video-appletv driver
info: [media] loading video-chromecast driver
info: [media] loading video-roku driver
info: [motive] loading automatic-vehicle driver
info: [motive] loading crazyflie-3d driver
info: [motive] loading irobot-floor driver
info: [motive] loading lockitron-lock driver
info: [motive] loading tesla-model-s driver
info: [presence] loading fob driver
info: [presence] loading mobile-mqtt driver
info: [presence] loading reelyactive-tag driver
info: [switch] loading insteon-dimmer driver
info: [switch] loading insteon-onoff driver
info: [switch] loading wemo-onoff driver
info: [switch] loading wink-onoff driver
info: [switch] loading wink-pivot-power-genius driver
info: [switch] loading zwave-dimmer driver
info: [switch] loading zwave-onoff driver
info: [wearable] loading watch driver
notice: [steward] start uuid=2f402f80-da50-11e1-9b23-001c42055f14
info: [server] listening on wss://_:8888
info: [server] listening on wss://_:8887
info: [server] listening on http://*:80
info: [server] loading console route
info: [server] loading manage route
info: [server] loading oneshot route
info: [server] loading root route
info: [server] loading ble discovery
info: [server] loading mac discovery
info: [server] loading owl discovery
info: [server] loading portscan discovery
info: [server] loading ssdp discovery
info: [server] loading tsrp discovery
info: [discovery] OWL driver listening on multicast udp://224.192.32.19:22600
info: [discovery] SSDP listening on http://192.168.0.118:1900
info: [discovery] TSRP listening on multicast udp://224.0.9.1:22601
info: [discovery] UPnP listening on http://192.168.0.118:8886
info: [discovery] mDNS Bedroom Apple TV url=http://192.168.0.106:7000/
info: [discovery] mDNS Living Room Apple TV url=http://192.168.0.115:7000/
info: [devices] found Bedroom Apple TV deviceID=5, deviceType=/device/media/appletv/video
info: [devices] found Living Room Apple TV deviceID=6, deviceType=/device/media/appletv/video
info: [discovery] UPnP front house lights url=http://192.168.0.125:49153/
info: [devices] found front house lights deviceID=3, deviceType=urn:Belkin:device:lightswitch:1
info: [discovery] UPnP hallway url=http://192.168.0.122:49153/
info: [discovery] UPnP hallway  3way door url=http://192.168.0.124:49154/
info: [discovery] UPnP WeMo Radio url=http://192.168.0.129:49153/
info: [devices] found hallway deviceID=2, deviceType=urn:Belkin:device:lightswitch:1
info: [devices] found hallway  3way door deviceID=1, deviceType=urn:Belkin:device:lightswitch:1
info: [devices] found WeMo Radio deviceID=4, deviceType=urn:Belkin:device:controllee:1
info: [sensor] loading nest-smoke driver
info: [sensor] loading texas-instruments-sensortag driver
info: [sensor] loading wemo-motion driver
info: [sensor] loading wink-spotter driver
info: [sensor] loading yoctopuce-4-20mA-Rx driver
info: [sensor] loading yoctopuce-co2 driver
info: [sensor] loading yoctopuce-light driver
info: [sensor] loading yoctopuce-voc driver
info: [switch] device/3 front house lights subscribe=uuid:f0dde92c-1dd1-11b2-b2ae-9a5eb6f4d8b2, sequence=0, seconds=1800
info: [switch] device/2 hallway subscribe=uuid:f1c06bbc-1dd1-11b2-8b21-b841277d4b89, sequence=0, seconds=1800
info: [switch] device/1 hallway  3way door subscribe=uuid:f49e8db4-1dd1-11b2-b30b-a0ac840bd3e6, sequence=0, seconds=1800
info: [switch] device/4 WeMo Radio subscribe=uuid:f57373ee-1dd1-11b2-b57d-e3c1487596ae, sequence=0, seconds=1800
warning: [steward] place/1 Home event=getWeather, diagnostic=check in 2368.472 seconds
info: [server] wss 127.0.0.1 39622 /console loopback=true, subnet=false, local=true, remoteAddress=127.0.0.1, secure=false, event=connection
info: [server] wss 127.0.0.1 39623 /console loopback=true, subnet=false, local=true, remoteAddress=127.0.0.1, secure=false, event=connection
info: [server] wss 127.0.0.1 39624 /manage loopback=true, subnet=false, local=true, remoteAddress=127.0.0.1, secure=false, event=connection
info: [discovery] UPnP VPN Router TL-R600VPN url=
warning: [devices] no maker registered for TL-R600VPN
info: [server] wss 127.0.0.1 39625 /manage loopback=true, subnet=false, local=true, remoteAddress=127.0.0.1, secure=false, event=connection
info: [server] wss 127.0.0.1 39627 /console loopback=true, subnet=false, local=true, remoteAddress=127.0.0.1, secure=false, event=connection
info: [server] wss 127.0.0.1 39628 /manage loopback=true, subnet=false, local=true, remoteAddress=127.0.0.1, secure=false, event=connection
info: [discovery] PORT starting scan
info: [discovery] PORT finished scan
info: [gateway] nest-cloud begin 30-second scan
notice: [steward] perform taskID=1, perform=on, parameter={}
notice: [steward] perform taskID=3, perform=off, parameter={}
notice: [steward] perform taskID=2, perform=off, parameter={}
notice: [steward] perform taskID=3, perform=off, parameter={}
notice: [steward] perform taskID=1, perform=on, parameter={}
notice: [steward] perform taskID=3, perform=off, parameter={}
notice: [steward] perform taskID=2, perform=off, parameter={}
notice: [steward] perform taskID=3, perform=off, parameter={}
notice: [steward] perform taskID=1, perform=on, parameter={}
notice: [steward] perform taskID=3, perform=off, parameter={}
notice: [steward] perform taskID=2, perform=off, parameter={}
notice: [steward] perform taskID=3, perform=off, parameter={}
notice: [steward] perform taskID=1, perform=on, parameter={}
notice: [steward] perform taskID=3, perform=off, parameter={}
notice: [steward] perform taskID=2, perform=off, parameter={}
notice: [steward] perform taskID=3, perform=off, parameter={}
info: [discovery] PORT starting scan
info: [discovery] PORT finished scan
info: [gateway] nest-cloud begin 30-second scan

**Comment by mrose17** [comment]
ok, help me with the terminology so i can understand what it's doing.

let's just deal in "device 1" and "device 2"

i think what the logs say is this (starting with the notice entries for 'perform'):

d1 & d2 were off.
you turned d1 on and: d1 got turned off and d2 got turned on.
you turned d1 on again and: d1 and d2 both got turned off.

i think this was done for a total of four times (acceding to the logs).

is that accurate?

**Comment by danielsza** [comment]
Sorry I'll try and be more clear about it.

d1&d2 were both off

I turned d1 on, then d2 turns on, then d1 turns off (works as it should)
I turned d1 on, then d2 turns off, then d1 turns off (works as it should)

So I do it again
I turned d1 on, then d2 turns on, then d1 turns off (works as it should)
I turned d1 on, then d2 turns off, then d1 turns off (works as it should)

but now d2 turns on (without pressing anything)
then d2 turns off (without pressing anything)

after this if I turn d1 on, nothing happens

if I restart the steward it works again for little while

**Comment by mrose17** [comment]
thanks. i am able to duplicate the problem and am looking into it.

**Comment by danielsza** [comment]
Ok great... At least it's not just me

**Comment by mrose17** [comment]
when the steward discovers a WeMo switch, it tells the switch to notify it when the switch changes state.

it appears that the issue is that the WeMo switch stops sending notifications to the steward after the second time.

i have modified the steward to re-request notifications, and to short-circuit some round-trip interactions.

so "get the latest" and see how that works for you.

**Comment by danielsza** [comment]
so far so good..

I’ll play with in for the next few days and let you know

Thanks Again

Daniel

**Comment by mrose17** [comment]
great! let me know how it goes…  enjoy! and thanks for your patience.
