### ISSUE TITLE
Steward seems to crash

### ISSUE THREAD

**Issue by GuySawyer** [TheThingSystem/node-taas-client#3]
Good day, thanks for updating the install information Mr. Rose. I had to copy test3.js into my install location though. It wasn't being installed with npm -l install taas-client. I hope that isn't a factor in this issue.

So, I editted the info in test3.js from

```
// fill-these in please...
  var clientID = '.../...'
    , loginCode = speakeasy.totp({ key      : '................................................................'
                                 , length   : 6
                                 , encoding : 'base32'
                                 , step     : 30 })
    ;
```

to

```
// fill-these in please...
  var clientID = 'admin/1'
    , loginCode = speakeasy.totp({ key      : '................................................................'
                                 , length   : 6
                                 , encoding : 'base32'
                                 , step     : 30 })
    ;
```

But I am not sure what to put in the "key" part?

I moved on with it like this for now. Then I ran test.js from node-thing-client and the macguffin connected and ran smoothly.
Then I ran test3.js. This was the resulting output:

```
debian@steward:~/node_modules/taas-client$ sudo node test3.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
console
{ event: 'establish', url: 'wss://steward.local.:8888/console' }
open console
ready console data=["developer"]
open management
ready management data={"role":"monitor"}
ready, set, go!
console close
```

My first issue is that it seems to have connected without error and without me putting anything into the "key" info as mentioned earlier.

Second issue is that the Steward seems to crash. "ready, set, go!" is printed to the log, after which it should send the perform command to the macguffin. Instead it closes. The macguffin code also hits close and stops running.

Your thoughts?

**Comment by GuySawyer** [comment]
I did some more testing, just want to add what I did.

I accessed the Steward via the d3 client and added a new master user called guest.
I then took the key information from the barcode scan, and added that to the test3.js file.
The login section of test3.js now looks like this:

```
// fill-these in please...
  var clientID = 'guest/4'
    , loginCode = speakeasy.totp({ key      : 'GVLEEZ3OPFLEG6SBOU4WQ6TPPFFEQ2ZUGVHEWSLGIMZTOV2QNY3HM3SPO5JW653N'
                                 , length   : 6
                                 , encoding : 'base32'
                                 , step     : 30 })
    ;
```

I am however still getting the same problem as described above.

**Comment by mrose17** [comment]
hi. the issue is most likely that your steward is in developer mode, as such, there's no need to login. because of that, when the 'open' event is emitted by the library, the loginP parameter is always false. the library is telling test3.js that there's no need to login.

however, i'm going to update the test files to indicate this…

with respect to the crash, if you can reproduce it, please attach the console output from the steward. i haven't seen any crashes in _that_ code for a while (-;

**Comment by GuySawyer** [comment]
Ok I see. The Steward was in developer mode. I'll run it in strict mode to make sure this is the case.

Elementary question but, how do I get the console output from the Steward?

**Comment by mrose17** [comment]
you can find it usually in /var/log/ … if not:

```
    # sh /etc/init.d/stewart stop
    # cd steward/steward/
    # ./run.sh
```

good luck!

**Comment by GuySawyer** [comment]
I found the log in /var/log/... it is long and I'm not sure where the relevant info is. It is also too large for me to dump in pastebin. What should I do?

**Comment by mrose17** [comment]
try this:

```
    sh /etc/init.d/steward stop
    rm  /var/log/steward.log
    sh /etc/init.d/steward start
```

now see if it crashes. if so, then pastebin the file.

**Comment by GuySawyer** [comment]
Not to worry. I used ./run.sh and caught the crash live. Here is the Steward log.

```
warning: [steward] place/1 Home event=getWeather, diagnostic=check in 1955.603 seconds
info: [discovery] PORT starting scan
info: [discovery] PORT finished scan
info: [server] wss 192.168.2.102 54227 /manage loopback=false, subnet=true, local=true, remoteAddress=192.168.2.102, remotePort=54227, secure=true, clientSerialNo=0, event=connection
notice: [manage] wss 192.168.2.102 54227 /manage loopback=false, subnet=true, local=true, remoteAddress=192.168.2.102, remotePort=54227, secure=true, clientSerialNo=0, event=login, userID=2, clientID=.things/3
info: [devices] found All-Ears Noise Detector deviceID=1, deviceType=/device/sensor/macguffin/sound
info: [server] wss 192.168.2.103 39008 /console loopback=false, subnet=true, local=true, remoteAddress=192.168.2.103, remotePort=39008, secure=true, clientSerialNo=1, event=connection
info: [server] wss 192.168.2.103 39009 /manage loopback=false, subnet=true, local=true, remoteAddress=192.168.2.103, remotePort=39009, secure=true, clientSerialNo=2, event=connection
alert: [steward] exception diagnostic=Cannot set property '98706053' of undefined
alert: [steward] exception stack=[{"fileName":"/home/debian/steward/steward/api/api-manage-thing.js","lineNumber":606,"functionName":"Thing.perform","typeName":"Thing","methodName":"perform","columnNumber":21,"native":false},{"fileName":"[as route] (/home/debian/steward/steward/api/api-manage-actor.js","lineNumber":215,"functionName":"Object.exports.perform","typeName":"Object","methodName":"exports.perform","columnNumber":54,"native":false},{"fileName":"/home/debian/steward/steward/routes/route-manage.js","lineNumber":76,"functionName":"","typeName":"WebSocket","methodName":null,"columnNumber":22,"native":false},{"fileName":"events.js","lineNumber":98,"functionName":"WebSocket.EventEmitter.emit","typeName":"WebSocket","methodName":"EventEmitter.emit","columnNumber":17,"native":false},{"fileName":"/home/debian/steward/steward/node_modules/ws/lib/WebSocket.js","lineNumber":647,"functionName":"Receiver.self._receiver.ontext","typeName":"Receiver","methodName":"self._receiver.ontext","columnNumber":10,"native":false},{"fileName":"/home/debian/steward/steward/node_modules/ws/lib/Receiver.js","lineNumber":397,"functionName":"Receiver.opcodes.1.finish","typeName":"Receiver","methodName":"opcodes.1.finish","columnNumber":14,"native":false},{"fileName":"/home/debian/steward/steward/node_modules/ws/lib/Receiver.js","lineNumber":378,"functionName":"Receiver.expectHandler","typeName":"Receiver","methodName":"expectHandler","columnNumber":33,"native":false},{"fileName":"/home/debian/steward/steward/node_modules/ws/lib/Receiver.js","lineNumber":93,"functionName":"Receiver.add","typeName":"Receiver","methodName":"add","columnNumber":24,"native":false},{"fileName":"/home/debian/steward/steward/node_modules/ws/lib/WebSocket.js","lineNumber":627,"functionName":"CleartextStream.firstHandler","typeName":"CleartextStream","methodName":"firstHandler","columnNumber":22,"native":false},{"fileName":"events.js","lineNumber":95,"functionName":"CleartextStream.EventEmitter.emit","typeName":"CleartextStream","methodName":"EventEmitter.emit","columnNumber":17,"native":false}]
uncaught exception: TypeError: Cannot set property '98706053' of undefined
Press ^C to exit or wait 10 seconds to restart
```

The first bit with wss 192.168.2.102 is when I ran the node-thing-client with the macguffin. After that updated its state about 3 times, I ran the node-taas-client from 192.168.2.103. ie, it is running on the same machine as the Steward.

**Comment by mrose17** [comment]
just checking: are you on the current version of the steward?

```
    cd steward/
    git pull upstream master
    cd steward/
    npm -l install
```

restart steward, etc.?

**Comment by GuySawyer** [comment]
'upstream' does not appear to be a git repository..?

**Comment by mrose17** [comment]
my guess is that you got the steward by downloading steward-master.zip from github. i'm not sure why they elide the .git information, but they do.

if that's the case, then try this:

```
    git clone https://github.com/TheThingSystem/steward.git
    cd steward/steward
    npm install -l
```

**Comment by GuySawyer** [comment]
I initially installed it using the sdcard image. But I remember updating it using the git clone. Will do that now. Should I repeat the test and log check after?

Simple issues here.. 'Steward' path already exists and is not empty? except I remember updating like this last time..

**Comment by mrose17** [comment]
if it came from the sdcard image, try 

```
git pull master
```

and see if that works!

**Comment by GuySawyer** [comment]
still, 'master' does not appear to be a git repo.
Also says the remote end hung up unexpectedly.. Don't know if that is relevant?

**Comment by mrose17** [comment]
ok, try just 

```
    git pull
```

**Comment by GuySawyer** [comment]
Haha, the simplest things. That worked. Now I npm -l install? and then..

**Comment by mrose17** [comment]
right

```
cd steward/
npm -l install
```

**Comment by GuySawyer** [comment]
ok great. When this is done, I will run the tests again and capture the steward log.

Thanks so much for your time btw. What time will you be online till, I understand it must be late for you?

**Comment by mrose17** [comment]
good luck! i am on us/pt and will be signing off in a few minutes; however, i was hoping we could at least get things moving on this issue…and we have.

**Comment by GuySawyer** [comment]
Hopefully the new version sorts things out, otherwise I will bash onward till tomorrow.
Thanks

**Comment by GuySawyer** [comment]
Update solved the problem, taas-client is working.
Thanks for your help.

**Comment by mrose17** [comment]
groovy!
