### ISSUE TITLE
Implementing Magic

### ISSUE THREAD

**Issue by GuySawyer** [TheThingSystem/node-taas-client#4]
I'm back! And now that I have my beaglebone slaves more or less setup, I'm working on the client side of things.
Going through the clients and magic pages of thethingsystem.com, there is very little documentation on the API calls and less info on magic.

Can you refer me to a manual of sorts? Or a couple good examples?

I'm trying to:
a. Have the steward report device states back to the client (which is then viewable through the webpage I'm creating)
b. Give the user control of devices via the webpage (this one I have sort of achieved)
c. Allow the use to build custom rules (or custom magic) from the client (ie. webpage)

This is just a little tricky without a guide or a manual for the steward API.

Thanks in advance
Guy

**Comment by mrose17** [comment]
thanks for the question. here are the brief answers. it may be useful to submit a PR adding things to the README.md file…

a. whenever the steward notices a change, the 'actor' event is emitted.
b. to control a device, use one of the perform\* methods.
c. this is outside the scope of the library.

does this make sense?

**Comment by GuySawyer** [comment]
Yes, that makes sense. a and b are not too complicated, my biggest concern is c.

When you say outside the scope of the library, do you mean taas-client is not capable of performing that function? ie. Not capable of creating Activities for the Steward. (Activities being "if this then that" type rules, as I understand it. Or is that focussed on the "custom" sense of the rule creation?

To fill in, what I am busy doing is writing a web server to interface with the user. The web interface will allow the user to select devices, sensors and commands by way of dropdown box. Thereafter, the script within the interface will put together the Steward command to create an activity, and this will be communicated to the steward via the taas-client.

I hope that clears up my intentions.

**Comment by mrose17** [comment]
as an aside, you may want to take a look at https://github.com/cantino/huginn/pull/368 and https://github.com/TheThingSystem/steward/issues/243

the node-taas-client is meant to be used by an application that implements [c] - there isn't any "business logic" in node-taas-client - you need to figure out what you want to do and then implement that logic.

however, based on your description, we're not talking about magic. we're talking about something similar to the HTML5/D3 client. you can use node-taas-client for that, though you would need to remove the node dependencies. the HTML5/D3 client and the developer clients use websocket calls directly. take a look at console.html to see the easy way of doing this.

**Comment by GuySawyer** [comment]
Ok I will take a look at those links properly on Monday, Just wanted to post a response now.

I understand that node-taas-client is meant to be used by an application that implements [c]. That is what I mean to achieve with the Web Server I mentioned earlier.

I'm not sure that it is exactly similar to the HTML5/D3 client, although I haven't yet had a look at console.html to understand fully what you mean. But after reading the TTS description of Magic, it is similar to what I am trying to achieve.

For example. A lamp is connected to the system via a BBB slave and can be monitored and controlled using my Webserver. My webserver uses the node-taas-client in the background to control the lamp via the Steward.
On top of that, there is a motion sensor connected and monitored in the same way.

I want to then give the user the ability, via my Webserver, to select the motion sensor and the lamp to be incorporated into a rule.
ie. a couple drop down boxes are given like this: (drop downs are represented by [] )
When/If [device] [comparator] [state], then [device] [comparator] [state].

So, The example above would be selected like this:
When/If [Motion Sensor] [Equals] [Motion Detected], then [Lamp] [Equals] [On].

So ultimately, the node-taas-client doesn't generate the rule, the user will with the user interface. The node-taas-client allows me to communicate this to the Steward.
My big problem is, I am at a bit of a loss when it comes to generating rules (or magic) for the Steward as the documentation on the TTS page regarding magic is quite short.

**Comment by mrose17** [comment]
based on https://github.com/TheThingSystem/node-taas-client/issues/5 - i think this is on track. if i'm wrong, let me know...
