### ISSUE TITLE
Pulling info from the event object in .onmessage

### ISSUE THREAD

**Issue by GuySawyer** [TheThingSystem/node-taas-client#5]
I have three sensors connected to the Steward reporting their states. The taas-client is watching for event messages from the Steward. This code waits for the event message and displays it:

```
ws.onmessage = function(event) {
    var str = JSON.stringify(JSON.parse(event.data), null, 2);
    console.log("Socket message: " + str);
    console.log("TESTING #######  : " + event.data.)
};
```

And here is the output:

```
Socket message: {
  ".updates": [
    {
      "whatami": "/device/sensor/rs/light",
      "whoami": "device/2",
      "name": "Light Sensor 1",
      "status": "light",
      "info": {
        "light": 1
      },
      "updated": 1402596238677
    },
    {
      "whatami": "/device/sensor/rs/motion",
      "whoami": "device/3",
      "name": "Motion Sensor 1",
      "status": "motion",
      "info": {
        "motion": 1
      },
      "updated": 1402596238677
    },
    {
      "whatami": "/device/switch/rs/light",
      "whoami": "device/4",
      "name": "Light Switch 1",
      "status": "off",
      "info": {
        "switch1": 0
      },
      "updated": 1402596238677
    }
  ]
}
```

I want to extract the "status" and "name" values to be displayed on my web server interface, but I can't figure out how to do that elegantly, partly because I can't figure out what the object parameters of "event" are, without a loop physically searching for the info.

Any suggestions?

**Comment by mrose17** [comment]
you're not using the API from this package. with the package, i'd do this:

```
    .on('actor', function(whoami, whatami) {
        var actor  = this.actors[whoami]
          , name   = actor.name
          , status = actor.status;
    })
```

if you want to use the raw websockets, then you want something like this:

```
    .on('message', function(event) {
        var updates = (!!event.data) && (event.data['.updates']);
        if (!updates) return;

        var actor, i;
        for (i = 0; i < updates.length; i++) {
          actor = updates[i];
        }

    })
```

**Comment by GuySawyer** [comment]
Ok, Im a little behind you here. What is the API from this package, and what is "the package" exactly?

Then, let's say I'm going to do it the first way you described:

```
    .on('actor', function(whoami, whatami) {
        var actor  = this.actors[whoami]
          , name   = actor.name
          , status = actor.status;
    })
```

I understand that the callback function provides the "whoami" and "whatami" objects. Then in the rest of the code, you only use "whoami" to initialise the "actor" object. From that, you get the name and status. So which devices name and status is going to end up in "name" and "status"?

I do realise this is trivial in your case, I apologise for my simplicity.
Regards
Guy

**Comment by mrose17** [comment]
sorry, i was unclear… i'm talking about node-taas-client. take a look at test.js in that directory, there's an event handler for the 'actor' event. every time that event fires, it's saying "a change is being reported for the actor identified by 'whoami' who has deviceType 'whatami' - in most cases, that's enough to let you know whether you want to care or not. if you do care, then you can use this.actors (maintained by the node-taas-package)… does that make sense?

**Comment by GuySawyer** [comment]
Ok, got it! That makes sense. I went and took the:

```
.on('actor', function(whoami, whatami) {
        var actor  = this.actors[whoami]
          , name   = actor.name
          , status = actor.status;
})
```

Section of code, and inserted it into my client.js (which is basically a modified version of test3.js). This is deeper workings of the Steward that I'm figuring out here. Is there a good reference manual on the Steward somewhere that might help before I come to you with these little issues?

Lastly, to add one more layer to this question. Rather than hard coding the device ID's, I will like to retrieve the list of device ID's from the Steward to be stored. They will then be used to determine who's status information is coming in with the above information so I can display it correctly.
I thought maybe the "listDevice" function would be the way to go here, and in that case, this code from test.js:

```
}).on('ready', function(channel, data) {
  console.log('ready ' + channel + ' data='+ JSON.stringify(data));

  if (channel !== 'management') return;

  console.log('ready, set, go!');
  steward.listDevice(null, { depth: 'all' }, function(message) {
    console.log(require('util').inspect(message, { depth: null }));
  });
```

Produces this:

```
console
{ event: 'establish', url: 'wss://steward.local.:8888/console' }
open console
ready console data=["developer"]
open management
ready management data={"role":"monitor"}
ready, set, go!
{ requestID: '2',
  result: 
   { devices: 
      { 'device/2': 
         { whatami: '/device/sensor/rs/light',
           name: 'Light Sensor 1',
           status: 'absent',
           info: { light: 0.5027777777777778, threshold: 50 },
           updated: {} },
        'device/3': 
         { whatami: '/device/sensor/rs/motion',
           name: 'Motion Sensor 1',
           status: 'absent',
           info: { motion: 1 },
           updated: {} },
        'device/4': 
         { whatami: '/device/switch/rs/light',
           name: 'Light Switch 1',
           status: 'absent',
           info: { switch1: 0 },
           updated: {} },
        'device/5': 
         { whatami: '/device/switch/quickswitch/dimmer',
           name: 'Dimmer',
           status: 'absent',
           info: { setting: 0, threshold: 0 },
           updated: {} } },
     actors: 
      { '/device/sensor/rs/light': 
         { observe: [ 'light' ],
           perform: [ 'shine' ],
           properties: { name: true, status: [ 'dark', 'light' ], light: 'Light' } },
        '/device/sensor/rs/motion': 
         { observe: [ 'motion' ],
           perform: [ 'move' ],
           properties: { name: true, status: [ 'motion', 'stationary' ], motion: 'm' } },
        '/device/switch/rs/light': 
         { observe: [ 'state' ],
           perform: [ 'toggle' ],
           properties: { name: true, status: [ 'On', 'Off' ], state: [ 'on', 'off' ] } },
        '/device/switch/quickswitch/dimmer': 
         { observe: [ 'state' ],
           perform: [ 'Set' ],
           properties: 
            { name: true,
              status: [ 'On', 'Off' ],
              setting: '%',
              threshold: '%' } } } } }
```

How can I extract all the deviceID and Name info from the "devices" section of that output?
Once again, I am sure it is trivial. But I still don't fully understand how this info is stored.

Regards
Guy

**Comment by mrose17** [comment]
sorry for the delay in replying. if we look at this snippet, you'll see that the objects contained in message.result.devices are identified by strings such as "device/2" - this is the "whoami" value. 

```
    { requestID: '2',
      result: 
       { devices: 
          { 'device/2': 
             { whatami: '/device/sensor/rs/light',
               name: 'Light Sensor 1',
               status: 'absent',
               info: { light: 0.5027777777777778, threshold: 50 },
               updated: {} },
```

to get a deviceID from a whoami value, simply take the text following the '/', e.g., 

```
    for (whoami in message.result.devices) if (message.result.devices.hasOwnProperty(whoami)) {
        var deviceID = whoami.split('/')[1];
        …
    }
```

does that make sense?

**Comment by GuySawyer** [comment]
Wow, yes. That makes complete sense. But that simple "for" statement makes me realise how little I actually know about the details of javascript.

I will only get a chance to try this tomorrow evening. But I will let you know how it goes.
Thanks a lot.

**Comment by mrose17** [comment]
closed due to lack of comment. if the issues remains, please commend and this issue can be re-opened!
